vich_uploader:
    db_driver: orm

    mappings:
        user_avatar:
            uri_prefix: /uploads/avatars
            upload_destination: '%kernel.project_dir%/public/uploads/avatars'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        animal_image:
            uri_prefix: /uploads/animals
            upload_destination: '%kernel.project_dir%/public/uploads/animals'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        post_image:
            uri_prefix: /uploads/posts
            upload_destination: '%kernel.project_dir%/public/uploads/posts'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        user_cover:
            uri_prefix: /uploads/covers
            upload_destination: '%kernel.project_dir%/public/uploads/covers'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
